### ISSUE TITLE
No se instala el paquete

### ISSUE THREAD

**Issue by lsaravia** [kbqt14/PaqueteAnalisisdeEstres#1]
Hola,

No se instala el paquete porque tiene varios problemas, todo el codigo que pongas dentro de R tiene que funcionar. 

```
> install_github("kbqt14/PaqueteExamenUNGS")
Downloading GitHub repo kbqt14/PaqueteExamenUNGS@master
from URL https://api.github.com/repos/kbqt14/PaqueteExamenUNGS/zipball/master
Installing PaqueteCeibo
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpMACnd5/devtools2d6941a92fe0/kbqt14-PaqueteExamenUNGS-0a7c311'  \
  --library='/home/leonardo/R/x86_64-pc-linux-gnu-library/3.5' --install-tests 

* installing *source* package ‘PaqueteCeibo’ ...
** R
** byte-compile and prepare package for lazy loading
Error in eval(exprs[i], envir) : object 'ins' not found
Error : unable to load R code in package ‘PaqueteCeibo’
ERROR: lazy loading failed for package ‘PaqueteCeibo’
* removing ‘/home/leonardo/R/x86_64-pc-linux-gnu-library/3.5/PaqueteCeibo’
Installation failed: Command failed (1)
```

Revisar las recomendaciones que di en el curso para el desarrollo de paquetes
y tambien podes mirar

http://r-pkgs.had.co.nz/r.html

> Use <-, not =, for assignment.

> Don’t use library() or require(). These modify the search path, affecting what functions are available from the global environment. It’s better to use the DESCRIPTION to specify your package’s requirements, as described in the next chapter. This also makes sure those packages are installed when your package is installed.

> Never use source() to load code from a file. source() modifies the current environment, inserting the results of executing the code. Instead, rely on devtools::load_all() which automatically sources all files in R/. If you’re using source() to create a dataset, instead switch to data/ as described in datasets.

ver el paquete de ejemplo del curso

https://github.com/lsaravia/PaqueGato

**Comment by kbqt14** [comment]
Hola profesor, seguí las recomendaciones pertinentes y creo que pude corregir los errores. Me llevo tiempo hacerlo porque quería hacer algo que me sirva también.
Le paso el paquete.
install_github("kbqt14/PaqueteExamenUNGS")
Saludos Cordiales
