### ISSUE TITLE
El paquete se instala pero no se tiene ninguna indicación de como usarlo

### ISSUE THREAD

**Issue by lsaravia** [kbqt14/PaqueteAnalisisdeEstres#2]
No tiene la ayuda definida con los roxygen2, no puedo saber que funciones tiene, o como usarlo.

ver 

http://r-pkgs.had.co.nz/man.html

**Comment by lsaravia** [comment]
Ok, ahora tiene ayuda, pero no funcionan la funciones

`PaqueteExamenUNGS::Tabla5()
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'Data/DatosCeibo.txt': No such file or directory`

fijate en http://r-pkgs.had.co.nz/data.html  en la seccion Raw Data, o tambien en los slides del curso.

**Comment by kbqt14** [comment]
Ahi le agregué la tabla modelo que se llama Datos Ceibo y debe estar en formato texto, en las intrucciones agregue ahora es que cuando se crea el proyecto debe existir una carpeta llamada Data y en esa carpeta debe estar esa tabla que puede ser tb modificada a mano hasta la semana 5. 
[DatosCeibo.txt](https://github.com/kbqt14/PaqueteExamenUNGS/files/2377101/DatosCeibo.txt)
La forma de llamar esta tabla en el .Rmd es DatosCeibo <-read.delim("Data/DatosCeibo.txt")

Saludos

**Comment by kbqt14** [comment]
Una vez cargada esa tabla en Data se puede usar así en el .Rmd para la semana5
install.packages("devtools")
require(devtools)
install_github("kbqt14/PaqueteExamenUNGS")
require("PaqueteExamenUNGS")
install.packages("dplyr")
require(dplyr)
DatosCeibo <-read.delim("Data/DatosCeibo.txt")
Tabla5(DatosCeibo)

**Comment by lsaravia** [comment]
Si yo instalo el paquete, no puedo leer ese archivo de texto

```
require(devtools)
install_github("kbqt14/PaqueteExamenUNGS")
require("PaqueteExamenUNGS")
DatosCeibo <-read.delim("Data/DatosCeibo.txt")

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'Data/DatosCeibo.txt': No such file or directory
```

**Comment by kbqt14** [comment]
El archivo que le pase era solo para que no arme de forma manual la tabla, en el Read me, puse las instrucciones para hacerlo

 "Los datos a importar deben estar contenidos en un bloc de notas, deben tener los siguientes titulos organizados en columnas Tratamiento	Semana	Longitud y se lo debe llamar DatosCeibo, el mismo debe estar en formato .txt. Este archivo Se debe importar a una carpeta nueva llamada "Data". Una vez en el .Rmd se debe llamar a este archivo de la siguiente manera, DatosCeibo <-read.delim("Data/DatosCeibo.txt") y darle run. Luego correr la función Tabla5(DatosCeibo) y se obtendrá la tabla del dia 5"

**Comment by lsaravia** [comment]
Si yo instalo el paquete no veo el readme, por eso lo que me explicás de la estructura de los datos deberia estar en la ayuda de la función. Los ejemplos deben funcionar, es decir deberías incluir el set de datos como se debe incluir raw data dentro del paquete, o lo podes incluir como set de datos de prueba que se carga automáticamente con el paquete, eso lo vimos en el curso, sino fijate http://r-pkgs.had.co.nz/data.html en la sección "Exported data"

**Comment by kbqt14** [comment]
Hola profesor buenas tardes, realicé algunas correcciones en base a la lectura de los materiales que me paso, espero funcione.
Saludos

**Comment by lsaravia** [comment]
Hola

Esto esta bien 

-Incluiste el archivo que vas a usar correctamente

Pero

- En la ayuda no está corregido

- Conceptualmente las funciones de un paquete trabajan por si solas por eso no esta bien en el ejemplo requerir otros paquetes. Es decir cuando necesitas usar otros paquete tenes que incluirlo en las dependencias.  (ver http://r-pkgs.had.co.nz/description.html) asi los otros paquetes si no existen se instalan automaticamente.

- la funcion Tabla5 tiene un parametro x que no utilizas, es decir no sirve para otra tabla porque la tabla esta fija, el parametro x deberia ser el nombre de la tabla. 

Saludos

**Comment by lsaravia** [comment]
Ok,

Los parametros de las funciones deben ser parametros reales:

```
falso_parametro <-function(x){

read.delim("nombredearchivo.txt")
}

```
en este caso no importa el valor que le pongas al parametro de la funcion siempre va leer el mismo archivo. El parametro esta definido pero no se usa. 

Eso es lo que pasa en las funciones que definiste.

**Comment by lsaravia** [comment]
Hola, quería ver si entendiste lo de los parametros de las funciones asi podemos cerrar el tema.

Saludos

**Comment by kbqt14** [comment]
Hola profesor buenas tardes, disculpe creí que el paquete ya estaba listo.

Debo de nuevo corregir lo de los parametros?

Yo hice el paquete para utilizarlo con mis datos es por eso que lo llamé asi.  Usted quiere que lo deje como Default el read.delim?

**Comment by lsaravia** [comment]
Una función que le pasas por parametro un nombre de archivo debe hacer algo con ese archivo, leer el archivo por ejemplo, pero en tus funciones eso no sucede. Eso tenes que cambiar y listo.

**Comment by kbqt14** [comment]
Hola Profesor. 

Realicé modificaciones en la función.
Resumiendo.
Dentro del proyecto que uno está ejecutando debe crear una carpeta Data.
Dentro de esa carpeta debe tener un archivo en txt llamado DatosTabla.txt
Las caracteristicas que debe contener el archivo estan dentro del paquete. pero basicamente son que esten ordenados con titulos organizados en columnas Tratamiento	Semana	Longitud
Le paso un archivo ejemplo
[DatosTabla.txt](https://github.com/kbqt14/PaqueteExamenUNGS/files/2485436/DatosTabla.txt)
Para ejectar sería.



install.packages("devtools")
require(devtools)
install_github("kbqt14/PaqueteExamenUNGS3")
require("PaqueteExamenUNGS3")
install.packages("dplyr")
require(dplyr)
DatosTabla <-read.delim("Data/DatosTabla.txt") 
Tabla3(DatosTabla)

**Comment by lsaravia** [comment]
Ok, listo!!

**Comment by kbqt14** [comment]
Holas buenas profesor, quisiera saber si ya tenemos calificacion del examen. Saludos
